import type { NextPage } from "next";
import Head from "next/head";
import axios from "axios";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const handleOauth = async () => {
    // const result = await axios.get(
    //   "https://github.com/login/oauth/authorize?client_id=4aaf785accf22320e7aa&redirect_url=http://localhost:3000/mainPage",
    //   {
    //     headers: {
    //       "Access-Control-Allow-Origin": "*",
    //     },
    //   },
    // );
    // console.log("result:  ", result);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <a href="https://github.com/login/oauth/authorize?client_id=4aaf785accf22320e7aa&redirect_url=http://localhost:3000/mainPage">
        github oauth
      </a>
    </div>
  );
};

export default Home;
